### ISSUE TITLE
LightGBM for Julia

### ISSUE THREAD

**Issue by azev77** [alan-turing-institute/MLJModels.jl#227]
LightGBM.jl is being updated to work w/ latest Julia & possibly moved to official repo by @wakakusa & @Allardvm.
See: [PR](https://github.com/Allardvm/LightGBM.jl/pull/22)
Also: @yalwan-iqvia is working on: https://github.com/IQVIA-ML/LightGBM.jl

Are these efforts coordinated?

**Comment by tlienart** [comment]
We know of all these repos yes, and the effort by Yaqub is the one we’re most familiar with :)

As far as I know Lightgbm is a bit of a pain to add to the ecosystem due to installation of binaries on many platforms but there’s hope to resolve this, it will be exciting to have it along side XGBoost for sure

**Comment by azev77** [comment]
Yes, yuge pain

**Comment by yalwan-iqvia** [comment]
Hi @azev77 we're actually very close to a release which would appear into this repository. I'd be happy if you'd like to try it out once it appears, since you seem to have a need?

**Comment by yalwan-iqvia** [comment]
I believe latest MLJModels can now load in LightGBM, does this mean this issue can be closed?

**Comment by tlienart** [comment]
yes
