### ISSUE TITLE
target_scitype for multi-target predictions

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/MLJModels.jl#40]
Should it be

* `AbstractMatrix{MLJBase.Continuous}` or
* `MLJBase.Table(MLJBase.Continuous)` ?

For now I've assumed it was the latter (in #39) given that I imagine the user would want to do `y=table[:, [1, 2]]` which would yield a table still.

**Comment by ablaom** [comment]
Yes, let's go for the latter. There is still the question of which particular table should be output. For consistency, with what transformers currently do, I suggest we match the type of the training target. In this case, if the raw row vectors are, say `y1` and `y2`, then we output construct a named tuple `t=(Column1=y1, Column2=y2)` and output `MLJBase.table(t, prototype  = y)`, where `X` was the input table. If we know the original names, we can use those instead of :Column1 and :Column2 but these would have to be bundled with the fitresult to make available to predict :-(  In the sk-learn wrap you are working on, I'm guessing there are no column names to start with, so this isn't an issue?

**Comment by ablaom** [comment]
Okay, I see that in #39 the multi-target methods assume the training `y` is a matrix, not a table. Although I am torn on this issue, I am inclined to agree with @fkiraly that table input should be allowed. We could also allow matrix input, but always output a table. I will suggest implementation details on #39
