### ISSUE TITLE
target_scitype, subtyping or not?

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/MLJModels.jl#43]
Should it be

`AbstractVector{<:Continuous}` or `AbstractVector{Continuous}` ? [this issue](https://github.com/alan-turing-institute/MLJ.jl/issues/225) seems to suggest it's the former but we currently have both in the interfaces as far as I can tell (e.g. in the ElasticNet from sklearn: https://github.com/alan-turing-institute/MLJModels.jl/blob/9eba97a96a9e3378cdac75aa474cce598d11da36/src/ScikitLearn.jl#L880 https://github.com/alan-turing-institute/MLJModels.jl/blob/9eba97a96a9e3378cdac75aa474cce598d11da36/src/ScikitLearn.jl#L888 and

**Comment by ablaom** [comment]
As `Continuous` has no subtypes (it is actually a concrete struct) I don't think it makes a difference. (Note however the `Finite` does have subtypes, because it is parameterised by N, and because `Multiclass<:Finite` and `OrderedFactor<:Finite`.

I started doing `AbstractVector{<:Continuous}` for aesthetic reasons.
